import type { DemoFolder, DemoProduct, DemoState } from './types';

const now = new Date('2026-05-09T10:00:00Z');
const ago = (hours: number) =>
  new Date(now.getTime() - hours * 3600 * 1000).toISOString();

const folders: DemoFolder[] = [
  {
    id: 'f-math',
    name: 'Математика',
    description: 'Курсы и вебинары по школьной и вузовской математике',
    parentId: null,
    emoji: '🧮',
    updatedAt: ago(36),
  },
  {
    id: 'f-algebra',
    name: 'Алгебра',
    description: 'Уравнения, многочлены, линейные пространства',
    parentId: 'f-math',
    emoji: '🔢',
    updatedAt: ago(50),
  },
  {
    id: 'f-linear',
    name: 'Линейная алгебра',
    description: 'Векторы, матрицы, определители',
    parentId: 'f-algebra',
    emoji: '📊',
    updatedAt: ago(72),
  },
  {
    id: 'f-geometry',
    name: 'Геометрия',
    description: 'Планиметрия и стереометрия',
    parentId: 'f-math',
    emoji: '📐',
    updatedAt: ago(96),
  },
  {
    id: 'f-physics',
    name: 'Физика',
    description: 'Механика, термодинамика, оптика',
    parentId: null,
    emoji: '⚛️',
    updatedAt: ago(24),
  },
  {
    id: 'f-mechanics',
    name: 'Механика',
    description: 'Кинематика, динамика, законы сохранения',
    parentId: 'f-physics',
    emoji: '⚙️',
    updatedAt: ago(60),
  },
  {
    id: 'f-chemistry',
    name: 'Химия',
    description: 'Общая, органическая и неорганическая',
    parentId: null,
    emoji: '🧪',
    updatedAt: ago(120),
  },
];

const COVERS = [
  { from: 'oklch(0.72 0.18 30)', to: 'oklch(0.45 0.22 350)', emoji: '🧮' },
  { from: 'oklch(0.78 0.16 220)', to: 'oklch(0.45 0.22 270)', emoji: '📐' },
  { from: 'oklch(0.78 0.18 145)', to: 'oklch(0.45 0.22 195)', emoji: '🧪' },
  { from: 'oklch(0.85 0.16 90)', to: 'oklch(0.55 0.22 30)', emoji: '🧲' },
  { from: 'oklch(0.78 0.18 320)', to: 'oklch(0.42 0.22 290)', emoji: '🔬' },
  { from: 'oklch(0.82 0.16 50)', to: 'oklch(0.5 0.22 5)', emoji: '🪐' },
  { from: 'oklch(0.78 0.18 175)', to: 'oklch(0.4 0.22 245)', emoji: '🧠' },
  { from: 'oklch(0.78 0.18 110)', to: 'oklch(0.45 0.22 165)', emoji: '🌱' },
] as const;

const products: DemoProduct[] = [
  {
    id: 'p-quad',
    type: 'course',
    status: 'published',
    title: 'Квадратные уравнения',
    description:
      'Полный курс с разбором всех типов задач: от базовых до олимпиадных.',
    durationHours: 24,
    lessons: 18,
    cover: COVERS[0],
    folderId: 'f-algebra',
    updatedAt: ago(12),
  },
  {
    id: 'p-poly',
    type: 'course',
    status: 'published',
    title: 'Многочлены и их корни',
    description:
      'Теорема Безу, схема Горнера, целые и рациональные корни. Готовимся к экзамену.',
    durationHours: 18,
    lessons: 14,
    cover: COVERS[1],
    folderId: 'f-algebra',
    updatedAt: ago(18),
  },
  {
    id: 'p-matrices',
    type: 'course',
    status: 'draft',
    title: 'Матрицы и определители',
    description:
      'От базовых операций до решения систем линейных уравнений методом Крамера.',
    durationHours: 32,
    lessons: 22,
    cover: COVERS[6],
    folderId: 'f-linear',
    updatedAt: ago(48),
  },
  {
    id: 'p-vectors',
    type: 'webinar',
    status: 'published',
    title: 'Векторные пространства',
    description:
      'Открытый вебинар: что такое базис, размерность и почему это важно.',
    durationHours: 2,
    lessons: 1,
    cover: COVERS[4],
    folderId: 'f-linear',
    updatedAt: ago(8),
  },
  {
    id: 'p-triangles',
    type: 'course',
    status: 'published',
    title: 'Треугольники и подобие',
    description:
      'Все признаки равенства и подобия, теоремы и десятки задач для отработки.',
    durationHours: 20,
    lessons: 16,
    cover: COVERS[1],
    folderId: 'f-geometry',
    updatedAt: ago(30),
  },
  {
    id: 'p-circles',
    type: 'course',
    status: 'archived',
    title: 'Окружность и угол',
    description:
      'Вписанные и центральные углы, касательные и хорды. Архивный курс прошлого года.',
    durationHours: 16,
    lessons: 12,
    cover: COVERS[5],
    folderId: 'f-geometry',
    updatedAt: ago(720),
  },
  {
    id: 'p-newton',
    type: 'course',
    status: 'published',
    title: 'Законы Ньютона',
    description:
      'Три закона, силы, инерциальные системы отсчёта. Базовый курс по механике.',
    durationHours: 28,
    lessons: 20,
    cover: COVERS[3],
    folderId: 'f-mechanics',
    updatedAt: ago(20),
  },
  {
    id: 'p-energy',
    type: 'course',
    status: 'draft',
    title: 'Работа и энергия',
    description:
      'Кинетическая и потенциальная энергия, законы сохранения. Готовится к публикации.',
    durationHours: 22,
    lessons: 16,
    cover: COVERS[5],
    folderId: 'f-mechanics',
    updatedAt: ago(4),
  },
  {
    id: 'p-optics',
    type: 'webinar',
    status: 'published',
    title: 'Геометрическая оптика',
    description:
      'Открытый вебинар про линзы, зеркала и построение изображений.',
    durationHours: 2,
    lessons: 1,
    cover: COVERS[4],
    folderId: 'f-physics',
    updatedAt: ago(72),
  },
  {
    id: 'p-thermo',
    type: 'course',
    status: 'published',
    title: 'Термодинамика. Первое начало',
    description:
      'Внутренняя энергия, теплота, работа газа. Курс с лабораторными задачами.',
    durationHours: 30,
    lessons: 22,
    cover: COVERS[3],
    folderId: 'f-physics',
    updatedAt: ago(60),
  },
  {
    id: 'p-organic',
    type: 'course',
    status: 'published',
    title: 'Органическая химия. Основы',
    description:
      'Углеводороды, функциональные группы, изомерия. Полный курс для старшей школы.',
    durationHours: 36,
    lessons: 28,
    cover: COVERS[2],
    folderId: 'f-chemistry',
    updatedAt: ago(96),
  },
  {
    id: 'p-reactions',
    type: 'webinar',
    status: 'draft',
    title: 'Скорость реакций',
    description:
      'Кинетика химических реакций: что влияет на скорость и как это рассчитать.',
    durationHours: 2,
    lessons: 1,
    cover: COVERS[7],
    folderId: 'f-chemistry',
    updatedAt: ago(2),
  },
  {
    id: 'p-intro',
    type: 'course',
    status: 'published',
    title: 'Подготовка к экзамену: общий план',
    description:
      'Стратегия подготовки: как распределить время, чему уделить больше внимания.',
    durationHours: 8,
    lessons: 6,
    cover: COVERS[6],
    folderId: null,
    updatedAt: ago(6),
  },
  {
    id: 'p-essay',
    type: 'webinar',
    status: 'published',
    title: 'Как читать научные тексты',
    description:
      'Бесплатный вебинар про учебники, статьи и оригинальные источники.',
    durationHours: 1,
    lessons: 1,
    cover: COVERS[7],
    folderId: null,
    updatedAt: ago(40),
  },
];

export const INITIAL_DEMO_STATE: DemoState = {
  folders,
  products,
};
