import type { DemoFolder, DemoProduct, DemoState } from './types';

const folders: DemoFolder[] = [
  { id: 'f-math', name: 'Математика', parentId: null, emoji: '∑' },
  { id: 'f-algebra', name: 'Алгебра', parentId: 'f-math', emoji: '𝑥' },
  { id: 'f-linear', name: 'Линейная алгебра', parentId: 'f-algebra', emoji: '⟂' },
  { id: 'f-geometry', name: 'Геометрия', parentId: 'f-math', emoji: '△' },
  { id: 'f-physics', name: 'Физика', parentId: null, emoji: '⚛' },
  { id: 'f-mechanics', name: 'Механика', parentId: 'f-physics', emoji: '⚙' },
  { id: 'f-chemistry', name: 'Химия', parentId: null, emoji: '⚗' },
];

const COVERS = [
  { from: 'oklch(0.72 0.18 30)', to: 'oklch(0.45 0.22 350)', emoji: '🧮' },
  { from: 'oklch(0.78 0.16 220)', to: 'oklch(0.45 0.22 270)', emoji: '📐' },
  { from: 'oklch(0.78 0.18 145)', to: 'oklch(0.45 0.22 195)', emoji: '🧪' },
  { from: 'oklch(0.85 0.16 90)', to: 'oklch(0.55 0.22 30)', emoji: '🧲' },
  { from: 'oklch(0.78 0.18 320)', to: 'oklch(0.42 0.22 290)', emoji: '🔬' },
  { from: 'oklch(0.82 0.16 50)', to: 'oklch(0.5 0.22 5)', emoji: '🪐' },
  { from: 'oklch(0.78 0.18 175)', to: 'oklch(0.4 0.22 245)', emoji: '🧠' },
  { from: 'oklch(0.78 0.18 110)', to: 'oklch(0.45 0.22 165)', emoji: '🌱' },
] as const;

const products: DemoProduct[] = [
  {
    id: 'p-quad',
    type: 'course',
    status: 'published',
    title: 'Квадратные уравнения',
    durationHours: 24,
    cover: COVERS[0],
    folderId: 'f-algebra',
  },
  {
    id: 'p-poly',
    type: 'course',
    status: 'published',
    title: 'Многочлены и их корни',
    durationHours: 18,
    cover: COVERS[1],
    folderId: 'f-algebra',
  },
  {
    id: 'p-matrices',
    type: 'course',
    status: 'draft',
    title: 'Матрицы и определители',
    durationHours: 32,
    cover: COVERS[6],
    folderId: 'f-linear',
  },
  {
    id: 'p-vectors',
    type: 'webinar',
    status: 'published',
    title: 'Вебинар: Векторные пространства',
    durationHours: 2,
    cover: COVERS[4],
    folderId: 'f-linear',
  },
  {
    id: 'p-triangles',
    type: 'course',
    status: 'published',
    title: 'Треугольники и подобие',
    durationHours: 20,
    cover: COVERS[1],
    folderId: 'f-geometry',
  },
  {
    id: 'p-circles',
    type: 'course',
    status: 'archived',
    title: 'Окружность и угол',
    durationHours: 16,
    cover: COVERS[5],
    folderId: 'f-geometry',
  },
  {
    id: 'p-newton',
    type: 'course',
    status: 'published',
    title: 'Законы Ньютона',
    durationHours: 28,
    cover: COVERS[3],
    folderId: 'f-mechanics',
  },
  {
    id: 'p-energy',
    type: 'course',
    status: 'draft',
    title: 'Работа и энергия',
    durationHours: 22,
    cover: COVERS[5],
    folderId: 'f-mechanics',
  },
  {
    id: 'p-optics',
    type: 'webinar',
    status: 'published',
    title: 'Вебинар: Геометрическая оптика',
    durationHours: 2,
    cover: COVERS[4],
    folderId: 'f-physics',
  },
  {
    id: 'p-thermo',
    type: 'course',
    status: 'published',
    title: 'Термодинамика. Первое начало',
    durationHours: 30,
    cover: COVERS[3],
    folderId: 'f-physics',
  },
  {
    id: 'p-organic',
    type: 'course',
    status: 'published',
    title: 'Органическая химия. Основы',
    durationHours: 36,
    cover: COVERS[2],
    folderId: 'f-chemistry',
  },
  {
    id: 'p-reactions',
    type: 'webinar',
    status: 'draft',
    title: 'Вебинар: Скорость реакций',
    durationHours: 2,
    cover: COVERS[7],
    folderId: 'f-chemistry',
  },
  {
    id: 'p-intro',
    type: 'course',
    status: 'published',
    title: 'Подготовка к экзамену: общий план',
    durationHours: 8,
    cover: COVERS[6],
    folderId: null,
  },
  {
    id: 'p-essay',
    type: 'webinar',
    status: 'published',
    title: 'Вебинар: Как читать научные тексты',
    durationHours: 1,
    cover: COVERS[7],
    folderId: null,
  },
];

export const INITIAL_DEMO_STATE: DemoState = {
  folders,
  products,
};
